name: UsefullStuff
main: io.github.bloodynoseproduction.UsefullStuff
version: 0.0.1b
commands:
    moo:
        description:
        usage: /<command>
    cot:
       description:
       usage: /<command>